#!/bin/bash

set -e

#make sure scripts are runnable
chown -R root scripts/*.sh
chmod u+x scripts/*.sh

LUCEE_VERSION="5.1.0.34"
export LUCEE_VERSION="5.1.0.34"
JVM_MAX_HEAP_SIZE="512m"
export JVM_MAX_HEAP_SIZE="512m"

export JVM_MAX_HEAP_SIZE="512m"
export JVM_FILE="server-jre-8u51-linux-x64.gz"
export JVM_VERSION="1.8.0_51"

function separator {
  echo " "
  echo "------------------------------------------------"
  echo " "
}

#make sure scripts are runnable
chown -R root scripts/*.sh
chmod u+x scripts/*.sh

#download lucee
./scripts/200-lucee.sh
separator

#install tomcat
./scripts/300-tomcat.sh
separator

#install jvm
./scripts/400-jvm.sh
separator

#install nginx
./scripts/500-nginx.sh
separator




CATALINA_HOME=/usr/share/tomcat7-codedeploy
